export const Routes = {
  DEFAULT: '/',
  HOME: '/',
  COMMUNITY: '/community/',
  SEARCH: '/search/',
  AUTH_COMPLETE: '/auth-complete/',
  AUTH_DENIED: '/auth-denied/',
  AUTH_NOT_WHITELISTED: '/auth-not-whitelisted/',
  CLAIM: '/claim/',
  ARGUMENT: '/argument/',
  ELEMENT: '/element/',
  HIGHLIGHT: '/highlight/',
  COMMENT: '/comment/',
  CREATE: '/create/',
  BACK: '/story/back/',
  CHALLENGE: '/story/challenge/',
  HOW_IT_WORKS: '/how/',
  VALUES: '/values/',
  PROFILE: '/profile/',
  EDIT_PROFILE: '/edit',
  EDIT_PROFILE_FOLLOW: '/edit/follow',
  WALLET: '/wallet/',
  LEADERBOARD: '/leaderboard/',
  NOTIFICATIONS: '/notifications/',
  INVITES: '/invites',
  INVITES_ADMIN: '/invites-admin',
  SLASHES: '/slashes',

  LOGIN: '/login/',
  REGISTER: '/register/',
  VERIFY: '/register/verify/',
  ACCOUNT_RECOVERY: '/recovery/',
  ACCOUNT_RECOVERY_SENT: '/recovery/sent',
  ACCOUNT_RECOVERY_RESET: '/recovery/reset',
  ACCOUNT_RECOVERY_RESET_COMPLETE: '/recovery/complete',

  ONBOARDING_FOLLOW: '/onboarding/follow',

  BIO: '/register/bio',
};
